version: "3.7"

services:
  mariadb:
    image: mariadb:10.2.38
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: root123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 150M
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin" ,"ping", "--silent", "-p$MARIADB_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 40s


  # init data job
  initdata-job:
    depends_on:
      - mariadb
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    image: ${REPO_HOST}/roandocker/initdata-job:${IMAGE_TAG}
    environment: 
      MARIADB_SERVICE_HOST: "mariadb"
      SQL_FILE: "istioAlltime"
      GIT_BRANCH: "master"
      GITURL: "github.com/codeandcode0x/istioAlltime.git"
      GITUSER: ""
      GITPASSWD: ""
      MIGRATION: "MARIADB_SERVICE_HOST"
      DBUSER: "root"
      DBPASSWD: "root123"
      INTERVAL_TIME: "5"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 1
    

  # ticket backend
  ticket-manager:
    depends_on:
      - initdata-job
      - mariadb
    # depends_on:
      # initdata-job:
      #   condition: service_started
      # mariadb:
      #     condition: service_healthy
    image: ${REPO_HOST}/roandocker/ticket-manager:${IMAGE_TAG}
    command: /bin/sh -c "./ticket-manager"
    ports:
      - 8080:8080
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWD: root123
      DB_DATABASE: ticket
      DB_LOGMODE: "true"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 150M
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 40s


  # ticket frontend
  ticket-fronted:
    depends_on:
      - ticket-manager
    # depends_on:
      # ticket-manager:
      #   condition: service_healthy
    image: ${REPO_HOST}/roandocker/ticket-frontend:${IMAGE_TAG}
    command: /bin/sh -c "java -jar /root/ticket-frontend.jar"
    ports:
      - 8090:8090
    environment:
      DB_HOST: mariadb
      TICKET_MANAGER_HOST: http://ticket-manager:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 150M
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8090/actuator/health || exit 1"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 40s

volumes:
  todo-mysql-data: