version: "3.7"

services:
  mariadb:
    image: mariadb:10.2.38
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: root123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 150M
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin" ,"ping", "--silent", "-p$MARIADB_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 40s


  # ticket backend
  gin-scaffold:
    depends_on:
      - mariadb
    # depends_on:
      # initdata-job:
      #   condition: service_started
      # mariadb:
      #     condition: service_healthy
    image: ${REPO_HOST}/roandocker/gin-scaffold:${IMAGE_TAG}
    command: /bin/sh -c "./gin-scaffold"
    ports:
      - 8080:8080
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWD: root123
      DB_DATABASE: gin_scaffold
      DB_LOGMODE: "true"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 150M
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 40s

volumes:
  todo-mysql-data: